<a href="https://colab.research.google.com/github/amaljoseph/TensorflowLearnings/blob/master/001_Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
print(tf.__version__)

In [0]:
hello = tf.constant("Hello ")

In [0]:
yworld = tf.constant("World")

In [0]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [0]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [0]:
print(result)

b'Hello World'


In [0]:
a = tf.constant(10)
b = tf.constant(5)

In [0]:
a

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [0]:
print(a)

Tensor("Const_2:0", shape=(), dtype=int32)


In [0]:
tf.Session().run(a)

10

In [0]:
with tf.Session() as sess:
  result = sess.run(a+b)

In [0]:
print(result)

15


In [0]:
print(a)

Tensor("Const_2:0", shape=(), dtype=int32)


In [0]:
type(a)

tensorflow.python.framework.ops.Tensor

In [0]:
const  = tf.constant(10)

In [0]:
fill_mat = tf.fill((4,4), 10)

In [0]:
zeros = tf.zeros((4,4))

In [0]:
ones = tf.ones((4,4))

In [0]:
randn = tf.random_normal((4,4), mean = 0, stddev=1.0)

In [0]:
randu = tf.random_uniform((4,4), minval=0, maxval=1)

In [0]:
ops = [const, fill_mat, zeros, ones, randn, randu]

In [0]:
with tf.Session() as sess:
  for op in ops:
    print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.8987074   0.98017555 -0.42469808 -1.8549542 ]
 [ 0.87472457 -0.6020317  -1.2245291   0.83572817]
 [-0.6296539   1.0967683  -0.19153854  1.4017628 ]
 [-0.58600855 -0.629266   -1.7023      0.4201004 ]]
[[0.44650996 0.04233992 0.8508432  0.6027671 ]
 [0.7514839  0.07467759 0.7166703  0.8287978 ]
 [0.37405515 0.9779706  0.01399064 0.799003  ]
 [0.30196142 0.8760351  0.2719251  0.13238037]]


In [0]:
a = tf.constant([[1,2],
                [3, 4]])

In [0]:
sess = tf.InteractiveSession()

In [0]:
print(a.eval())

[[1 2]
 [3 4]]


In [0]:
a = tf.constant([[1,2], 
                [3, 4]])

In [0]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([[1,1],
                [1, 1]])

In [0]:
result = tf.matmul(a, b)

In [0]:
result.eval()

array([[3, 3],
       [7, 7]], dtype=int32)