<a href="https://colab.research.google.com/github/amaljoseph/TensorflowLearnings/blob/master/numpy-pandas-matplot-scikit/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [6]:
#convert python array into numpy array
my_list = [1,2,3]
type(my_list)
my_list = np.array(my_list)
type(my_list)

numpy.ndarray

In [9]:
#similar to python range
np.arange(0,10)
np.arange(0,10, 2) #step size note-integer

array([0, 2, 4, 6, 8])

**NP zeros, ones, linspace**

In [11]:
np.zeros((3,5))#NOTE- FLOATING POINT

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,11, 11) # 11 points btw 0 and 11 evenly spaced

array([ 0. ,  1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 11. ])

**Random Arrays**

In [23]:
np.random.randint(0,10)
np.random.randint(0,10, (3,3))

array([[0, 0, 7],
       [9, 7, 3],
       [8, 2, 8]])

In [26]:
# random seed - to get same random nos everytime - both should be same line
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

**Operations**

In [0]:
arr = np.random.randint(0, 100, 10)

In [28]:
arr.max()

93

In [29]:
arr.min()

4

In [30]:
arr.mean()

47.3

In [32]:
#index position of maxvalue -similar min
arr.argmax()

8

In [33]:
arr.reshape(2,5)

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

**Indexing**

In [0]:
mat = np.arange(0, 100).reshape(10,10)

In [35]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
#index location row-col
mat[0,1]

1

In [38]:
#slicing - like regular python slicing
# ':'=all rows    --- '0'=column0
mat[:, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
mat[5, :]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [40]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [43]:
my_filter = mat >50 #boolean check for size of each num
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])